### ISSUE TITLE
singularity run not working

### ISSUE THREAD

**Issue by jordandekraker** [khanlab/hippunfold#164] opened 2022-01-21 17:07 UTC
here is the error i'm getting:
```
$ singularity run hippunfold-v1.0.0.sif 
/.singularity.d/runscript: 3: exec: hippunfold: not found
```

**Comment by akhanf** [comment] 2022-01-21 17:16
ah that's strange, I tested the latest build a few commits ago -- I'll take a look to see what might be happening

**Comment by akhanf** [comment] 2022-01-21 17:32
I'm not able to reproduce your error after 
```
singularity pull docker://khanlab/hippunfold:v1.0.0
```
then running I get:
```


alik@AFI-CBS-H-6:/localscratch$ singularity run  ./hippunfold_v1.0.0.sif 
usage: hippunfold [-h] [--workflow-mode] [--force-conversion] [--retrofit]
                  [--help-snakemake]
                  [--participant-label PARTICIPANT_LABEL [PARTICIPANT_LABEL ...]]
                  [--exclude_participant_label EXCLUDE_PARTICIPANT_LABEL [EXCLUDE_PARTICIPANT_LABEL ...]]
                  --modality {T1w,T2w,hippb500,segT1w,segT2w,cropseg}
                  [--derivatives DERIVATIVES] [--skip_preproc] [--skip_coreg]
                  [--skip_inject_template_labels]
                  [--inject-template-smoothing-factor INJECT_TEMPLATE_SMOOTHING_FACTOR]
                  [--rigid-reg-template] [--no_reg_template]
                  [--template {CITI168,dHCP}] [--t1-reg-template] [--use_gpu]
                  [--nnunet-disable-tta]
                  [--output_spaces {native,T1w} [{native,T1w} ...]]
                  [--output-density {0p5mm,1mm,2mm,unfoldiso} [{0p5mm,1mm,2mm,unfoldiso} ...]]
                  [--hemi {L,R} [{L,R} ...]]
                  [--laminar-coords-method {laplace,equivolume}] [--keep-work]
                  [--force_nnunet_model {T1w,T2w,T1T2w,b1000,trimodal,hippb500,neonateT1w}]
                  [--filter-T2w FILTER_T2W [FILTER_T2W ...]]
                  [--filter-hippb500 FILTER_HIPPB500 [FILTER_HIPPB500 ...]]
                  [--filter-T1w FILTER_T1W [FILTER_T1W ...]]
                  [--filter-seg FILTER_SEG [FILTER_SEG ...]]
                  [--filter-cropseg FILTER_CROPSEG [FILTER_CROPSEG ...]]
                  [--wildcards-T2w WILDCARDS_T2W [WILDCARDS_T2W ...]]
                  [--wildcards-hippb500 WILDCARDS_HIPPB500 [WILDCARDS_HIPPB500 ...]]
                  [--wildcards-T1w WILDCARDS_T1W [WILDCARDS_T1W ...]]
                  [--wildcards-seg WILDCARDS_SEG [WILDCARDS_SEG ...]]
                  [--wildcards-cropseg WILDCARDS_CROPSEG [WILDCARDS_CROPSEG ...]]
                  [--path-T2w PATH_T2W] [--path-hippb500 PATH_HIPPB500]
                  [--path-T1w PATH_T1W] [--path-seg PATH_SEG]
                  [--path-cropseg PATH_CROPSEG]
                  bids_dir output_dir {participant,group}
hippunfold: error: the following arguments are required: bids_dir, output_dir, analysis_level, --modality
```

**Comment by akhanf** [comment] 2022-01-22 00:30
Closing this as it seems to be a local issue when building

**Closed by akhanf** 2022-01-22 00:30 UTC
Labels: bug
